### PR TITLE
Replace Jekyll with 11ty

### LINKED ISSUE #100: Replace Jekyll with 11ty
## Summary

- Replace Jekyll and remove its dependencies to support `dotrun`
- Update dockerfile and gitignore

### PR DESCRIPTION
**Pull request by carkod**
## Done

- Replace Jekyll with 11ty.
- Original `karmdown` library used by Jekyll does not seem to be available with 11ty, replaced by `markdown-it` (and its plugins) to make it work.
- Updated markup to be compatible with 11ty
- Updated ignore file for `dotrun`
- Updated `dockerfile` with new setup using 11ty.

## QA

1. Checkout this branch
2. `dotrun` and browse http://localhost:8024/
3. Check that navigation links work correctly
4. Check that Table of Contents appear correctly
5. Check that global navigation appears.

Fixes #100

### CODE REVIEW

**Comment by carkod** [comment]
@steverydz can you take a look when you can? the `compress.liquid` template doesn't seem to be very compatible out of the box, do we need to do some config? or do we need to rewrite it?
https://www.11ty.dev/docs/languages/liquid/

**Comment by steverydz** [comment]
@carkod this will fix your issue with that template - also fixed the css path and the navigation links https://github.com/steverydz/netplan.io/commit/d160d5634b7b058bc0561948caaadca76429a1fe

The compress layout was to minify the HTML, but we don't use that on any of the other sites, and as it doesn't work with 11ty we don't need it.

**Comment by jpmartinspt** [comment]
Table of contents seems broken in all pages.

**Comment by carkod** [comment]
@jpmartinspt can't reproduce, tried also on Firefox. I suppose you have `dotrun clean` first? Also, do you get any errors? is it possible that is caching?

**Comment by jpmartinspt** [comment]
Just tried in the demo, does not seem to work still.

**Comment by carkod** [comment]
Fixed. It was missing the eleventy file in the docker instructions, as in this case it is needed to run the ToC modules

**Pull request merged**
